### ISSUE TITLE
pacha-win.exe not working under windows 11

### ISSUE THREAD

**Issue by mirek190** [mounta11n/Pacha#1]
pacha-win.exe 1.0 not working under windows 11.
I run it .. is a blink for a split second and that it.

**Comment by mounta11n** [comment]
have you run the binary through command line or by double clicking? Or have you compiled by yourself?

**Comment by mirek190** [comment]
I used your  prebuiled .exe file .
Double clicked.

**Comment by maddes8cht** [comment]
As you have to provide the model with 
`-m \path\to\model.bin`
and this is not done when just double-clicking the exe, it will simply spit out an error message and close.


Anyway, i started from the commandline, providing a model, and i also just get an Error:
```
pacha-win.exe -m "X:\llama.cpp\models\orca-mini-7b.ggmlv3.q2_K.bin"
C:\snapshot\yazan_mk\Projects\js\_pacha\node_modules\blessed\lib\widgets\screen.js:309
  if (!this.program.isAlt) return;
                    ^

TypeError: Cannot read properties of undefined (reading 'isAlt')
    at Screen.leave (C:\snapshot\yazan_mk\Projects\js\_pacha\node_modules\blessed\lib\widgets\screen.js:309:21)
    at Screen.destroy (C:\snapshot\yazan_mk\Projects\js\_pacha\node_modules\blessed\lib\widgets\screen.js:411:8)
    at C:\snapshot\yazan_mk\Projects\js\_pacha\node_modules\blessed\lib\widgets\screen.js:216:14
    at Array.forEach (<anonymous>)
    at process.<anonymous> (C:\snapshot\yazan_mk\Projects\js\_pacha\node_modules\blessed\lib\widgets\screen.js:215:30)
    at process.emit (node:events:537:28)
    at process._fatalException (node:internal/process/execution:167:25)

Node.js v18.5.0
```


Didn't try to compile myself so far.

**Comment by mounta11n** [comment]
Sorry for the inconvenience. I tried the binary in a Windows 11 VM and have experienced the same behavior.

But I was able to run the app from source code. Please try it. First make sure you have installed nvm and node.

Then for dependencies `npm install blessed` and `npm install os-utils`.

After that you should be able to run the app with `node pacha.js`.

It is not necessary to specifiy a model/models path. Even if ./models/ is empty and even if there is no llama.cpp (./main) in the same folder, the app should start anyway.

Nevertheless, I am currently working on fixing the problem and hope to provide you with a solution soon.
